Automate install

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2,15 +2,68 @@
 
 echo "Life configuring ..."
 
-PREREQUESTIES="make g++ libsdl2-dev libgl1-mesa-dev "
-for prerequest in $PREREQUESTIES
+PREREQUESTIES=( \
+    "make" \
+    "g++" \
+    "mingw-w64" \
+    "libsdl2-dev" \
+    "libglew-dev" \
+)
+DOWNLOADS=( \
+    "https://www.libsdl.org/release/SDL2-devel-2.0.9-mingw.tar.gz" \
+    "http://www.grhmedia.com/glew/glew-2.1.0-mingw-w64.zip" \
+)
+PATHES=( \
+    "SDL2-2.0.9/x86_64-w64-mingw32/" \
+    "glew-2.1.0/" \
+)
+
+for ((i = 0; i < ${#PREREQUESTIES[@]}; ++i))
 do
-    if [ "$(dpkg -l | grep '^ii' | awk '{print $2}' | grep '^$prerequest\$')" == "" ]
+    if [ "$(dpkg -l | grep '^ii' | awk '{print $2}' | grep "^${PREREQUESTIES[i]}\(:\|$\)")" == "" ]
     then
-        sudo apt -y -qq install $prerequest
-    else
-        echo $prerequest is present.
+        if ! sudo apt -y -qq install ${PREREQUESTIES[i]}
+        then
+            echo "Failed to install ${PREREQUESTIES[i]}."
+            exit -1
+        fi
     fi
 done
+
+mkdir -p deps
+cd deps
+for ((i = 0; i < ${#DOWNLOADS[@]}; ++i))
+do
+    FileName=$(basename "${DOWNLOADS[i]}")
+    if [ ! -f ${FileName} ]
+    then
+        if ! wget ${DOWNLOADS[i]}
+        then
+            echo "Failed to download ${DOWNLOADS[i]}."
+            exit -1
+        fi
+        if [ $(echo ${FileName: -4} | tr '[:upper:]' '[:lower:]') == ".zip" ]
+        then
+            if ! unzip ${FileName}
+            then
+                echo "Failed to unzip ${FileName}."
+                exit -1
+            fi
+        elif [ $(echo ${FileName: -7} | tr '[:upper:]' '[:lower:]') == ".tar.gz" ]
+        then
+            if ! tar -xvzf ${FileName}
+            then
+                echo "Failed to unzip ${FileName}."
+                exit -1
+            fi
+        else
+            echo "Unknown file type ${FileName}."
+            exit -1
+        fi
+        sudo cp -r ${PATHES[i]}/lib/ /usr/x86_64-w64-mingw32/
+        sudo cp -r ${PATHES[i]}/include/ /usr/x86_64-w64-mingw32/
+    fi
+done
+cd ..
 
 echo "Life configured."
